"""Updated Password column in Employee Table

Revision ID: 355d1d20c962
Revises: 
Create Date: 2023-05-06 11:38:59.032853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '355d1d20c962'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    op.drop_table('projectexpenseclaims')
    op.drop_table('employeeprojects')
    with op.batch_alter_table('currency', schema=None) as batch_op:
        batch_op.alter_column('ExchangeRate',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=10),
               existing_nullable=True)

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('BankAccounterNumber', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        batch_op.alter_column('Password',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_constraint('employee_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('employee_ibfk_1', type_='foreignkey')
        batch_op.drop_column('BankAccountNumber')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('BankAccountNumber', mysql.VARCHAR(length=50), nullable=True))
        batch_op.create_foreign_key('employee_ibfk_1', 'employee', ['SupervisorID'], ['EmployeeID'])
        batch_op.create_foreign_key('employee_ibfk_2', 'department', ['DepartmentCode'], ['DepartmentCode'])
        batch_op.alter_column('Password',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('password_hash')
        batch_op.drop_column('BankAccounterNumber')

    with op.batch_alter_table('currency', schema=None) as batch_op:
        batch_op.alter_column('ExchangeRate',
               existing_type=sa.Numeric(precision=10, scale=10),
               type_=mysql.FLOAT(),
               existing_nullable=True)

    op.create_table('employeeprojects',
    sa.Column('ProjectID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('EmployeeID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ProjectName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('ProjectStatus', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ProjectBudget', mysql.FLOAT(), nullable=True),
    sa.Column('ProjectLeadID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['EmployeeID'], ['employee.EmployeeID'], name='employeeprojects_ibfk_1'),
    sa.ForeignKeyConstraint(['ProjectLeadID'], ['employee.EmployeeID'], name='employeeprojects_ibfk_2'),
    sa.PrimaryKeyConstraint('ProjectID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('projectexpenseclaims',
    sa.Column('ClaimID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ProjectID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('EmployeeID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('CurrencyID', mysql.VARCHAR(length=3), nullable=False),
    sa.Column('ExpenseDate', mysql.DATETIME(), nullable=False),
    sa.Column('Amount', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('Purpose', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('ChargeToDefaultDept', mysql.BIT(length=1), nullable=False),
    sa.Column('AlternativeDeptCode', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('Status', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('LastEditedClaimDate', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['CurrencyID'], ['currency.CurrencyID'], name='projectexpenseclaims_ibfk_3'),
    sa.ForeignKeyConstraint(['EmployeeID'], ['employee.EmployeeID'], name='projectexpenseclaims_ibfk_1'),
    sa.ForeignKeyConstraint(['ProjectID'], ['employeeprojects.ProjectID'], name='projectexpenseclaims_ibfk_2'),
    sa.PrimaryKeyConstraint('ClaimID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('department',
    sa.Column('DepartmentCode', mysql.VARCHAR(length=3), nullable=False),
    sa.Column('DepartmentName', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('DepartmentCode'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
